### ISSUE TITLE
NDR regional program: Incorrect program information

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp-backend#20]
During the broadcast of the regional programs between 7:30 p.m. and 8:00 p.m., "hallo niedersachsen" is incorrectly output for all regional channels, while the correct streams are actually being transmitted.

Samsung Galaxy XCover 4S
Android 10
Zapp 3.6.1

**Comment by cemrich** [comment]
Thank you very much for your report!

As this is a backend (EPG) issue I transfered this issue. It may not be possible to fix easily, because the ARD api does not provide detailed information about all NDR channels. A new scraper may be needed.

**Comment by WebworkrNet** [comment]
Can I be of assistance in any way?

**Comment by cemrich** [comment]
This issue should now be finally fixed for all regional channels. ARD updated their program info api.
