### ISSUE TITLE
Pull down to refresh live program list

### ISSUE THREAD

**Issue by Der-Flip** [mediathekview/zapp-backend#30]
The live program list at times happens to be out of date / lagging behind. Sometimes the program will not update up to 15 minutes past the program has ended.
A pull down to refresh option to force reload the entire program list would be very convenient as I have not yet found out how to force refresh this list. Closing and reopening the app doesn't seem to do it either.

In the screenshot below see 3sat being out of date for 7minutes at the moment of taking the screenshot, 
![Screenshot_2022-10-20-08-15-55-431_de.christinecoenen.code.zapp.jpg](https://user-images.githubusercontent.com/72888738/196870531-e7e65b5c-6411-489f-a4c2-03f74c46301b.jpg)

At 10 minutes it changed to "No program info"
![Screenshot_2022-10-20-08-17-42-273_de.christinecoenen.code.zapp.jpg](https://user-images.githubusercontent.com/72888738/196870731-7526543b-bdbf-4de8-9371-c6364ac3238b.jpg)

**Comment by cemrich** [comment]
This was an easy fix :)

The server time was off. I might have to add a metadata field sometime to find out what time the server thinks it is.
