### ISSUE TITLE
Unescaped html characters in ard downloader

### ISSUE THREAD

**Issue by cemrich** [mediathekview/zapp-backend#33]
Sample files with unsescaped quotes:
- [swr_rp.json.txt (from zapp api)](https://github.com/mediathekview/zapp-backend/files/12137150/swr_rp.json.txt)
- [Now.json.txt (from ard api)](https://github.com/mediathekview/zapp-backend/files/12137151/Now.json.txt)

**Comment by cemrich** [comment]
This has been fixed inside the client in mediathekview/zapp#439

**Comment by WebworkrNet** [comment]
Thanks for fixing this in release [8.5.3](https://github.com/mediathekview/zapp/releases/tag/v8.5.3).
