### ISSUE TITLE
Live stream "NDR" channels do not work

### ISSUE THREAD

**Issue by WebworkrNet** [mediathekview/zapp-backend#38]
## Which channel does not work correctly?

- NDR Hamburg
- NDR Mecklenburg-Vorpommern
- NDR Niedersachsen
- NDR Schleswig-Holstein

## What is the problem?
- [ ] does not load at all
- [ ] shows always the same looping content
- [ ] performance problem (stuttering or other)
- [X] other problem (add description)

In the "Live" tab, the program title of "NDR Niedersachsen" is displayed for all NDR regional programs, even if another special regional television program is running at the same time.

![Screenshot_20240719_180155_Zapp](https://github.com/user-attachments/assets/c123edc3-a8e4-4f37-bd4e-6e89d2ac7618)

**Comment by cemrich** [comment]
Okay, somewhere deep inside the ard program info api I found the missing channels. This issue should be fixed once the auto deployment has run. I'll close this issue after verification.

Thank you very much for your help!

**Comment by cemrich** [comment]
The changes are now online and should be picked up by Zapp automatically. Feel free to reopen or open a new issue, if the problem persists.

**Comment by WebworkrNet** [comment]
Looks fine.
Thanks for fixing. :-)
